import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { TooltipProvider } from "@swastik/ui/components/shadcn/tooltip";

const googleSansFlex = localFont({
  src: "../../../packages/ui/src/fonts/GoogleSansFlex.ttf",
  variable: "--font-googleSansFlex",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${googleSansFlex.className}`}>

        <TooltipProvider>

          {children}
        </TooltipProvider>
      </body>
    </html>
  );
}
